//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typographia.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.ProductMaterialRequirement = new HashSet<ProductMaterialRequirement>();
        }
    
        public int Id_equipment { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Type { get; set; }
        public Nullable<decimal> LoadPercentage { get; set; }
    
        public virtual Type_equipment Type_equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterialRequirement> ProductMaterialRequirement { get; set; }
    }
}
