//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typographia.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterialRequirement = new HashSet<ProductMaterialRequirement>();
        }
    
        public int Id_materials { get; set; }
        public string Name { get; set; }
        public Nullable<int> Min_kolichestvo { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Srok_godnosti { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterialRequirement> ProductMaterialRequirement { get; set; }
    }
}
