//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typographia.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id_notification { get; set; }
        public Nullable<int> Id_orders { get; set; }
        public Nullable<int> Id_material { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
